// Code generated by protoc-gen-go.
// source: commands.proto
// DO NOT EDIT!

/*
Package packets is a generated protocol buffer package.

It is generated from these files:
	commands.proto
	communication.proto

It has these top-level messages:
	Command
	Execute
	Packet
	GeneralErrorResponse
	IntroductionPassive
	RouterConfigurationRequest
	RoomConfigurationRequest
	DeviceTransferPassive
*/
package packets

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command struct {
	// Types that are valid to be assigned to Body:
	//	*Command_Execute
	Body isCommand_Body `protobuf_oneof:"body"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isCommand_Body interface {
	isCommand_Body()
}

type Command_Execute struct {
	Execute *Execute `protobuf:"bytes,1,opt,name=execute,oneof"`
}

func (*Command_Execute) isCommand_Body() {}

func (m *Command) GetBody() isCommand_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Command) GetExecute() *Execute {
	if x, ok := m.GetBody().(*Command_Execute); ok {
		return x.Execute
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Command) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Command_OneofMarshaler, _Command_OneofUnmarshaler, _Command_OneofSizer, []interface{}{
		(*Command_Execute)(nil),
	}
}

func _Command_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Command)
	// body
	switch x := m.Body.(type) {
	case *Command_Execute:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Execute); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Command.Body has unexpected type %T", x)
	}
	return nil
}

func _Command_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Command)
	switch tag {
	case 1: // body.execute
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Execute)
		err := b.DecodeMessage(msg)
		m.Body = &Command_Execute{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Command_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Command)
	// body
	switch x := m.Body.(type) {
	case *Command_Execute:
		s := proto.Size(x.Execute)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Execute struct {
	Core       string   `protobuf:"bytes,1,opt,name=core" json:"core,omitempty"`
	Parameters []string `protobuf:"bytes,2,rep,name=parameters" json:"parameters,omitempty"`
}

func (m *Execute) Reset()                    { *m = Execute{} }
func (m *Execute) String() string            { return proto.CompactTextString(m) }
func (*Execute) ProtoMessage()               {}
func (*Execute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Command)(nil), "packets.Command")
	proto.RegisterType((*Execute)(nil), "packets.Execute")
}

func init() { proto.RegisterFile("commands.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x48, 0x4c, 0xce,
	0x4e, 0x2d, 0x29, 0x56, 0xb2, 0xe7, 0x62, 0x77, 0x86, 0x48, 0x09, 0xe9, 0x70, 0xb1, 0xa7, 0x56,
	0xa4, 0x26, 0x97, 0x96, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x09, 0xe8, 0x41, 0x55,
	0xe9, 0xb9, 0x42, 0xc4, 0x3d, 0x18, 0x82, 0x60, 0x4a, 0x9c, 0xd8, 0xb8, 0x58, 0x92, 0xf2, 0x53,
	0x2a, 0x95, 0x6c, 0xb9, 0xd8, 0xa1, 0xb2, 0x42, 0x42, 0x5c, 0x2c, 0xc9, 0xf9, 0x45, 0x10, 0xdd,
	0x9c, 0x41, 0x60, 0xb6, 0x90, 0x1c, 0x17, 0x57, 0x41, 0x62, 0x51, 0x62, 0x6e, 0x6a, 0x49, 0x6a,
	0x51, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06, 0x67, 0x10, 0x92, 0x48, 0x12, 0x1b, 0xd8, 0x3d, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x6e, 0x35, 0xc7, 0xa1, 0x00, 0x00, 0x00,
}
