// Code generated by protoc-gen-go.
// source: communication.proto
// DO NOT EDIT!

/*
Package packets is a generated protocol buffer package.

It is generated from these files:
	communication.proto

It has these top-level messages:
	Wrapper
	IntroductionServer
	ConfigurationRequest
*/
package packets

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Wrapper_Header_Type int32

const (
	Wrapper_Header_REQUEST  Wrapper_Header_Type = 0
	Wrapper_Header_RESPONSE Wrapper_Header_Type = 1
	Wrapper_Header_SERVER   Wrapper_Header_Type = 2
)

var Wrapper_Header_Type_name = map[int32]string{
	0: "REQUEST",
	1: "RESPONSE",
	2: "SERVER",
}
var Wrapper_Header_Type_value = map[string]int32{
	"REQUEST":  0,
	"RESPONSE": 1,
	"SERVER":   2,
}

func (x Wrapper_Header_Type) String() string {
	return proto.EnumName(Wrapper_Header_Type_name, int32(x))
}
func (Wrapper_Header_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0, 0} }

type Wrapper struct {
	Header *Wrapper_Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*Wrapper_Intro
	Body isWrapper_Body `protobuf_oneof:"body"`
}

func (m *Wrapper) Reset()                    { *m = Wrapper{} }
func (m *Wrapper) String() string            { return proto.CompactTextString(m) }
func (*Wrapper) ProtoMessage()               {}
func (*Wrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isWrapper_Body interface {
	isWrapper_Body()
}

type Wrapper_Intro struct {
	Intro *IntroductionServer `protobuf:"bytes,2,opt,name=intro,oneof"`
}

func (*Wrapper_Intro) isWrapper_Body() {}

func (m *Wrapper) GetBody() isWrapper_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Wrapper) GetHeader() *Wrapper_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Wrapper) GetIntro() *IntroductionServer {
	if x, ok := m.GetBody().(*Wrapper_Intro); ok {
		return x.Intro
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Wrapper) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Wrapper_OneofMarshaler, _Wrapper_OneofUnmarshaler, _Wrapper_OneofSizer, []interface{}{
		(*Wrapper_Intro)(nil),
	}
}

func _Wrapper_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Wrapper)
	// body
	switch x := m.Body.(type) {
	case *Wrapper_Intro:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Intro); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Wrapper.Body has unexpected type %T", x)
	}
	return nil
}

func _Wrapper_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Wrapper)
	switch tag {
	case 2: // body.intro
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IntroductionServer)
		err := b.DecodeMessage(msg)
		m.Body = &Wrapper_Intro{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Wrapper_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Wrapper)
	// body
	switch x := m.Body.(type) {
	case *Wrapper_Intro:
		s := proto.Size(x.Intro)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Begin the header information. This is standard information
// across all packets that is necessary for basic functionality
// and/or routing.
type Wrapper_Header struct {
	Origin      string              `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Destination string              `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
	Id          string              `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Type        Wrapper_Header_Type `protobuf:"varint,4,opt,name=type,enum=packets.Wrapper_Header_Type" json:"type,omitempty"`
}

func (m *Wrapper_Header) Reset()                    { *m = Wrapper_Header{} }
func (m *Wrapper_Header) String() string            { return proto.CompactTextString(m) }
func (*Wrapper_Header) ProtoMessage()               {}
func (*Wrapper_Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// IntroductionServer is sent immediately upon opening of a socket
// from the server to the client. As this is not a request->response
// packet, it is named Server to indicate the one-sided nature.
// <br>
type IntroductionServer struct {
	Setup bool `protobuf:"varint,1,opt,name=setup" json:"setup,omitempty"`
}

func (m *IntroductionServer) Reset()                    { *m = IntroductionServer{} }
func (m *IntroductionServer) String() string            { return proto.CompactTextString(m) }
func (*IntroductionServer) ProtoMessage()               {}
func (*IntroductionServer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// ConfigurationRequest contains the information that needs to be
// configured on the router before it can function as a router.
// <br>
// As of the time of writing this, only the room name must be
// configured.
type ConfigurationRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ConfigurationRequest) Reset()                    { *m = ConfigurationRequest{} }
func (m *ConfigurationRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigurationRequest) ProtoMessage()               {}
func (*ConfigurationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Wrapper)(nil), "packets.Wrapper")
	proto.RegisterType((*Wrapper_Header)(nil), "packets.Wrapper.Header")
	proto.RegisterType((*IntroductionServer)(nil), "packets.IntroductionServer")
	proto.RegisterType((*ConfigurationRequest)(nil), "packets.ConfigurationRequest")
	proto.RegisterEnum("packets.Wrapper_Header_Type", Wrapper_Header_Type_name, Wrapper_Header_Type_value)
}

func init() { proto.RegisterFile("communication.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0xd7, 0xbe, 0x5d, 0xb6, 0x9d, 0xbd, 0x8c, 0x71, 0x1c, 0x5a, 0xd4, 0x8b, 0xd1, 0x2b,
	0x11, 0xac, 0xb2, 0x7d, 0x03, 0x25, 0x30, 0x6f, 0xfc, 0x93, 0x4e, 0xbd, 0xee, 0xda, 0x38, 0x83,
	0x34, 0x89, 0x69, 0x2a, 0xec, 0x43, 0x79, 0xe5, 0x17, 0xb4, 0x4d, 0x8b, 0x08, 0xe2, 0x5d, 0x9e,
	0xe7, 0xfc, 0x38, 0xe7, 0x79, 0x08, 0xec, 0x65, 0xaa, 0x28, 0x2a, 0x29, 0xb2, 0xd4, 0x0a, 0x25,
	0x63, 0x6d, 0x94, 0x55, 0x38, 0xd0, 0x69, 0xf6, 0xca, 0x6d, 0x19, 0x7d, 0xf8, 0x30, 0x78, 0x32,
	0xa9, 0xd6, 0xdc, 0xe0, 0x39, 0x90, 0x17, 0x9e, 0xe6, 0xdc, 0x84, 0xde, 0xdc, 0x3b, 0x19, 0x2f,
	0x0e, 0xe2, 0x8e, 0x8a, 0x3b, 0x22, 0x5e, 0xb9, 0x31, 0xeb, 0x30, 0x5c, 0x42, 0x5f, 0x48, 0x6b,
	0x54, 0xe8, 0x3b, 0xfe, 0xe8, 0x9b, 0xbf, 0x6e, 0xdc, 0xbc, 0xca, 0x9a, 0x8b, 0x09, 0x37, 0xef,
	0xdc, 0xac, 0x7a, 0xac, 0x65, 0x0f, 0x3f, 0x3d, 0x20, 0xed, 0x1e, 0xdc, 0x07, 0xa2, 0x8c, 0xd8,
	0x0a, 0xe9, 0x0e, 0x8e, 0x58, 0xa7, 0x70, 0x0e, 0xe3, 0x9c, 0x97, 0x56, 0x48, 0x17, 0xd9, 0x6d,
	0x1f, 0xb1, 0x9f, 0x16, 0x4e, 0xc0, 0x17, 0x79, 0xf8, 0xcf, 0x0d, 0xea, 0x17, 0x5e, 0x40, 0x60,
	0x77, 0x9a, 0x87, 0x41, 0xed, 0x4c, 0x16, 0xc7, 0x7f, 0x04, 0x8f, 0xd7, 0x35, 0xc3, 0x1c, 0x19,
	0x9d, 0x41, 0xd0, 0x28, 0x1c, 0xc3, 0x80, 0xd1, 0xfb, 0x07, 0x9a, 0xac, 0xa7, 0x3d, 0xfc, 0x0f,
	0x43, 0x46, 0x93, 0xbb, 0xdb, 0x9b, 0x84, 0x4e, 0x3d, 0x04, 0x20, 0x09, 0x65, 0x8f, 0x94, 0x4d,
	0xfd, 0x4b, 0x02, 0xc1, 0x46, 0xe5, 0xbb, 0xe8, 0x14, 0xf0, 0x77, 0x39, 0x9c, 0x41, 0xbf, 0xe4,
	0xb6, 0xd2, 0xae, 0xc7, 0x90, 0xb5, 0xa2, 0x66, 0x67, 0x57, 0x4a, 0x3e, 0x8b, 0x6d, 0x65, 0x5c,
	0x6a, 0xc6, 0xdf, 0xaa, 0xba, 0x03, 0x22, 0x04, 0x32, 0x2d, 0x78, 0x57, 0xda, 0xbd, 0x37, 0xc4,
	0xfd, 0xcb, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xba, 0x54, 0x9f, 0xae, 0x01, 0x00, 0x00,
}
