// Code generated by protoc-gen-go.
// source: communication.proto
// DO NOT EDIT!

package packets

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Packet_Header_Type int32

const (
	Packet_Header_REQUEST  Packet_Header_Type = 0
	Packet_Header_RESPONSE Packet_Header_Type = 1
	Packet_Header_PASSIVE  Packet_Header_Type = 2
)

var Packet_Header_Type_name = map[int32]string{
	0: "REQUEST",
	1: "RESPONSE",
	2: "PASSIVE",
}
var Packet_Header_Type_value = map[string]int32{
	"REQUEST":  0,
	"RESPONSE": 1,
	"PASSIVE":  2,
}

func (x Packet_Header_Type) String() string {
	return proto.EnumName(Packet_Header_Type_name, int32(x))
}
func (Packet_Header_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0, 0} }

type Packet struct {
	Header *Packet_Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*Packet_Intro
	//	*Packet_RouterConfigReq
	//	*Packet_RoomConfigReq
	//	*Packet_ErrorResponse
	//	*Packet_DeviceTransfer
	//	*Packet_Command
	Body isPacket_Body `protobuf_oneof:"body"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type isPacket_Body interface {
	isPacket_Body()
}

type Packet_Intro struct {
	Intro *IntroductionPassive `protobuf:"bytes,2,opt,name=intro,oneof"`
}
type Packet_RouterConfigReq struct {
	RouterConfigReq *RouterConfigurationRequest `protobuf:"bytes,3,opt,name=routerConfigReq,oneof"`
}
type Packet_RoomConfigReq struct {
	RoomConfigReq *RoomConfigurationRequest `protobuf:"bytes,4,opt,name=roomConfigReq,oneof"`
}
type Packet_ErrorResponse struct {
	ErrorResponse *GeneralErrorResponse `protobuf:"bytes,5,opt,name=errorResponse,oneof"`
}
type Packet_DeviceTransfer struct {
	DeviceTransfer *DeviceTransferPassive `protobuf:"bytes,6,opt,name=deviceTransfer,oneof"`
}
type Packet_Command struct {
	Command *Command `protobuf:"bytes,99,opt,name=command,oneof"`
}

func (*Packet_Intro) isPacket_Body()           {}
func (*Packet_RouterConfigReq) isPacket_Body() {}
func (*Packet_RoomConfigReq) isPacket_Body()   {}
func (*Packet_ErrorResponse) isPacket_Body()   {}
func (*Packet_DeviceTransfer) isPacket_Body()  {}
func (*Packet_Command) isPacket_Body()         {}

func (m *Packet) GetBody() isPacket_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Packet) GetHeader() *Packet_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Packet) GetIntro() *IntroductionPassive {
	if x, ok := m.GetBody().(*Packet_Intro); ok {
		return x.Intro
	}
	return nil
}

func (m *Packet) GetRouterConfigReq() *RouterConfigurationRequest {
	if x, ok := m.GetBody().(*Packet_RouterConfigReq); ok {
		return x.RouterConfigReq
	}
	return nil
}

func (m *Packet) GetRoomConfigReq() *RoomConfigurationRequest {
	if x, ok := m.GetBody().(*Packet_RoomConfigReq); ok {
		return x.RoomConfigReq
	}
	return nil
}

func (m *Packet) GetErrorResponse() *GeneralErrorResponse {
	if x, ok := m.GetBody().(*Packet_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

func (m *Packet) GetDeviceTransfer() *DeviceTransferPassive {
	if x, ok := m.GetBody().(*Packet_DeviceTransfer); ok {
		return x.DeviceTransfer
	}
	return nil
}

func (m *Packet) GetCommand() *Command {
	if x, ok := m.GetBody().(*Packet_Command); ok {
		return x.Command
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Packet) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Packet_OneofMarshaler, _Packet_OneofUnmarshaler, _Packet_OneofSizer, []interface{}{
		(*Packet_Intro)(nil),
		(*Packet_RouterConfigReq)(nil),
		(*Packet_RoomConfigReq)(nil),
		(*Packet_ErrorResponse)(nil),
		(*Packet_DeviceTransfer)(nil),
		(*Packet_Command)(nil),
	}
}

func _Packet_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Packet)
	// body
	switch x := m.Body.(type) {
	case *Packet_Intro:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Intro); err != nil {
			return err
		}
	case *Packet_RouterConfigReq:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RouterConfigReq); err != nil {
			return err
		}
	case *Packet_RoomConfigReq:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RoomConfigReq); err != nil {
			return err
		}
	case *Packet_ErrorResponse:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ErrorResponse); err != nil {
			return err
		}
	case *Packet_DeviceTransfer:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeviceTransfer); err != nil {
			return err
		}
	case *Packet_Command:
		b.EncodeVarint(99<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Command); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Packet.Body has unexpected type %T", x)
	}
	return nil
}

func _Packet_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Packet)
	switch tag {
	case 2: // body.intro
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IntroductionPassive)
		err := b.DecodeMessage(msg)
		m.Body = &Packet_Intro{msg}
		return true, err
	case 3: // body.routerConfigReq
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RouterConfigurationRequest)
		err := b.DecodeMessage(msg)
		m.Body = &Packet_RouterConfigReq{msg}
		return true, err
	case 4: // body.roomConfigReq
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RoomConfigurationRequest)
		err := b.DecodeMessage(msg)
		m.Body = &Packet_RoomConfigReq{msg}
		return true, err
	case 5: // body.errorResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GeneralErrorResponse)
		err := b.DecodeMessage(msg)
		m.Body = &Packet_ErrorResponse{msg}
		return true, err
	case 6: // body.deviceTransfer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeviceTransferPassive)
		err := b.DecodeMessage(msg)
		m.Body = &Packet_DeviceTransfer{msg}
		return true, err
	case 99: // body.command
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Command)
		err := b.DecodeMessage(msg)
		m.Body = &Packet_Command{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Packet_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Packet)
	// body
	switch x := m.Body.(type) {
	case *Packet_Intro:
		s := proto.Size(x.Intro)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Packet_RouterConfigReq:
		s := proto.Size(x.RouterConfigReq)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Packet_RoomConfigReq:
		s := proto.Size(x.RoomConfigReq)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Packet_ErrorResponse:
		s := proto.Size(x.ErrorResponse)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Packet_DeviceTransfer:
		s := proto.Size(x.DeviceTransfer)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Packet_Command:
		s := proto.Size(x.Command)
		n += proto.SizeVarint(99<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Begin the header information. This is standard information
// across all packets that is necessary for basic functionality
// and/or routing.
type Packet_Header struct {
	Origin      string             `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Destination string             `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
	Id          string             `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Type        Packet_Header_Type `protobuf:"varint,4,opt,name=type,enum=packets.Packet_Header_Type" json:"type,omitempty"`
	Route       []string           `protobuf:"bytes,5,rep,name=route" json:"route,omitempty"`
}

func (m *Packet_Header) Reset()                    { *m = Packet_Header{} }
func (m *Packet_Header) String() string            { return proto.CompactTextString(m) }
func (*Packet_Header) ProtoMessage()               {}
func (*Packet_Header) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

type GeneralErrorResponse struct {
	ErrorMessage string `protobuf:"bytes,1,opt,name=errorMessage" json:"errorMessage,omitempty"`
}

func (m *GeneralErrorResponse) Reset()                    { *m = GeneralErrorResponse{} }
func (m *GeneralErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*GeneralErrorResponse) ProtoMessage()               {}
func (*GeneralErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

// IntroductionPassive is sent immediately upon opening of a socket
// from the server to the client. As this is not a request->response
// packet, it is named Passive to indicate the one-sided nature.
// <br>
type IntroductionPassive struct {
	Setup bool `protobuf:"varint,1,opt,name=setup" json:"setup,omitempty"`
}

func (m *IntroductionPassive) Reset()                    { *m = IntroductionPassive{} }
func (m *IntroductionPassive) String() string            { return proto.CompactTextString(m) }
func (*IntroductionPassive) ProtoMessage()               {}
func (*IntroductionPassive) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

// RouterConfigurationRequest contains the information that needs to be
// configured on the router before it can function as a router.
// <br>
type RouterConfigurationRequest struct {
	Ssid     string `protobuf:"bytes,1,opt,name=ssid" json:"ssid,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *RouterConfigurationRequest) Reset()                    { *m = RouterConfigurationRequest{} }
func (m *RouterConfigurationRequest) String() string            { return proto.CompactTextString(m) }
func (*RouterConfigurationRequest) ProtoMessage()               {}
func (*RouterConfigurationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

// RoomConfigurationRequest contains information to configure and/or
// customize the room.
// <br>
type RoomConfigurationRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *RoomConfigurationRequest) Reset()                    { *m = RoomConfigurationRequest{} }
func (m *RoomConfigurationRequest) String() string            { return proto.CompactTextString(m) }
func (*RoomConfigurationRequest) ProtoMessage()               {}
func (*RoomConfigurationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

// DeviceTransferPassive notifies definers and phones that a device
// has paired with a new definer.
// <br>
type DeviceTransferPassive struct {
	Device string `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
}

func (m *DeviceTransferPassive) Reset()                    { *m = DeviceTransferPassive{} }
func (m *DeviceTransferPassive) String() string            { return proto.CompactTextString(m) }
func (*DeviceTransferPassive) ProtoMessage()               {}
func (*DeviceTransferPassive) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func init() {
	proto.RegisterType((*Packet)(nil), "packets.Packet")
	proto.RegisterType((*Packet_Header)(nil), "packets.Packet.Header")
	proto.RegisterType((*GeneralErrorResponse)(nil), "packets.GeneralErrorResponse")
	proto.RegisterType((*IntroductionPassive)(nil), "packets.IntroductionPassive")
	proto.RegisterType((*RouterConfigurationRequest)(nil), "packets.RouterConfigurationRequest")
	proto.RegisterType((*RoomConfigurationRequest)(nil), "packets.RoomConfigurationRequest")
	proto.RegisterType((*DeviceTransferPassive)(nil), "packets.DeviceTransferPassive")
	proto.RegisterEnum("packets.Packet_Header_Type", Packet_Header_Type_name, Packet_Header_Type_value)
}

func init() { proto.RegisterFile("communication.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x53, 0x5f, 0x6f, 0xd3, 0x30,
	0x10, 0x6f, 0xbb, 0x36, 0x6d, 0xaf, 0x5b, 0xa9, 0xbc, 0x31, 0x45, 0xe5, 0x8f, 0x4a, 0x78, 0x99,
	0x04, 0xca, 0xa4, 0xc1, 0x13, 0x6f, 0x30, 0x22, 0x5a, 0x09, 0x58, 0x71, 0x0b, 0xef, 0x5e, 0x7c,
	0x2b, 0x16, 0xd4, 0xce, 0xec, 0x64, 0xa8, 0x1f, 0x86, 0x0f, 0xc4, 0xb7, 0x42, 0xb9, 0xa4, 0x59,
	0xbb, 0x75, 0x6f, 0xb9, 0xfb, 0xfd, 0xb1, 0x7d, 0xbf, 0x0b, 0x1c, 0xc6, 0x66, 0xb9, 0xcc, 0xb4,
	0x8a, 0x45, 0xaa, 0x8c, 0x0e, 0x13, 0x6b, 0x52, 0xc3, 0xda, 0x89, 0x88, 0x7f, 0x61, 0xea, 0x86,
	0xfd, 0x1c, 0x15, 0x5a, 0xba, 0x02, 0x08, 0xfe, 0xb6, 0xc0, 0x9b, 0x12, 0xc6, 0x42, 0xf0, 0x7e,
	0xa2, 0x90, 0x68, 0xfd, 0xfa, 0xa8, 0x7e, 0xd2, 0x3b, 0x3b, 0x0e, 0x4b, 0x51, 0x58, 0x10, 0xc2,
	0x31, 0xa1, 0xbc, 0x64, 0xb1, 0xb7, 0xd0, 0x52, 0x3a, 0xb5, 0xc6, 0x6f, 0x10, 0xfd, 0x69, 0x45,
	0x9f, 0xe4, 0x5d, 0x99, 0xc5, 0xf9, 0xf9, 0x53, 0xe1, 0x9c, 0xba, 0xc1, 0x71, 0x8d, 0x17, 0x64,
	0x76, 0x01, 0x8f, 0xac, 0xc9, 0x52, 0xb4, 0xe7, 0x46, 0x5f, 0xa9, 0x05, 0xc7, 0x6b, 0x7f, 0x8f,
	0xf4, 0x2f, 0x2b, 0x3d, 0xdf, 0xc0, 0x33, 0x4b, 0xcf, 0xe0, 0x78, 0x9d, 0xa1, 0x4b, 0xc7, 0x35,
	0x7e, 0x57, 0xcd, 0x26, 0x70, 0x60, 0x8d, 0x59, 0xde, 0xda, 0x35, 0xc9, 0xee, 0xc5, 0x86, 0xdd,
	0x1a, 0xbd, 0x67, 0xb6, 0xad, 0x64, 0x11, 0x1c, 0xa0, 0xb5, 0xc6, 0x72, 0x74, 0x89, 0xd1, 0x0e,
	0xfd, 0x16, 0x59, 0x3d, 0xab, 0xac, 0x3e, 0xa1, 0x46, 0x2b, 0x7e, 0x47, 0x9b, 0xa4, 0xdc, 0x66,
	0x4b, 0xc5, 0xc6, 0xd0, 0x97, 0x78, 0xa3, 0x62, 0x9c, 0x5b, 0xa1, 0xdd, 0x15, 0x5a, 0xdf, 0x23,
	0x9f, 0xe7, 0x95, 0xcf, 0xc7, 0x2d, 0xf8, 0x76, 0x46, 0x77, 0x74, 0xec, 0x35, 0xb4, 0xcb, 0xbc,
	0xfc, 0x98, 0x2c, 0x06, 0x95, 0xc5, 0x79, 0xd1, 0x1f, 0xd7, 0xf8, 0x9a, 0x32, 0xfc, 0x57, 0x07,
	0xaf, 0xc8, 0x88, 0x1d, 0x83, 0x67, 0xac, 0x5a, 0x28, 0x4d, 0x59, 0x76, 0x79, 0x59, 0xb1, 0x11,
	0xf4, 0x24, 0xba, 0x54, 0x69, 0x1a, 0x04, 0x25, 0xd7, 0xe5, 0x9b, 0x2d, 0xd6, 0x87, 0x86, 0x92,
	0x14, 0x49, 0x97, 0x37, 0x94, 0x64, 0xa7, 0xd0, 0x4c, 0x57, 0x09, 0xd2, 0x54, 0xfb, 0x67, 0x4f,
	0x76, 0xef, 0x44, 0x38, 0x5f, 0x25, 0xc8, 0x89, 0xc8, 0x8e, 0xa0, 0x45, 0x11, 0xf9, 0xad, 0xd1,
	0xde, 0x49, 0x97, 0x17, 0x45, 0x10, 0x42, 0x33, 0xe7, 0xb0, 0x1e, 0xb4, 0x79, 0xf4, 0xed, 0x7b,
	0x34, 0x9b, 0x0f, 0x6a, 0x6c, 0x1f, 0x3a, 0x3c, 0x9a, 0x4d, 0x2f, 0xbe, 0xce, 0xa2, 0x41, 0x3d,
	0x87, 0xa6, 0xef, 0x67, 0xb3, 0xc9, 0x8f, 0x68, 0xd0, 0xf8, 0xe0, 0x41, 0xf3, 0xd2, 0xc8, 0x55,
	0xf0, 0x0e, 0x8e, 0x76, 0x0d, 0x9d, 0x05, 0xb0, 0x4f, 0x43, 0xff, 0x82, 0xce, 0x89, 0x05, 0x96,
	0xcf, 0xdc, 0xea, 0x05, 0xaf, 0xe0, 0x70, 0xc7, 0x2a, 0xe6, 0x17, 0x74, 0x98, 0x66, 0x09, 0x69,
	0x3a, 0xbc, 0x28, 0x82, 0xcf, 0x30, 0x7c, 0x78, 0xef, 0x18, 0x83, 0xa6, 0x73, 0x4a, 0x96, 0xc7,
	0xd0, 0x37, 0x1b, 0x42, 0x27, 0x11, 0xce, 0xfd, 0x31, 0x56, 0x96, 0x83, 0xac, 0xea, 0x20, 0x04,
	0xff, 0xa1, 0xb5, 0xcb, 0xbd, 0xb4, 0x58, 0xae, 0xaf, 0x4c, 0xdf, 0xc1, 0x29, 0x3c, 0xde, 0xb9,
	0x13, 0x79, 0x90, 0xc5, 0x4e, 0xac, 0x83, 0x2c, 0xaa, 0x4b, 0x8f, 0x7e, 0xdf, 0x37, 0xff, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xcf, 0x51, 0xb4, 0xc7, 0xee, 0x03, 0x00, 0x00,
}
